- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 3600 # 1hr floof
    - !type:DepartmentTimeRequirement
<<<<<<< HEAD
<<<<<<< HEAD
      department: Epistemics # DeltaV - Epistemics Department replacing Science
<<<<<<< HEAD
      min: 3600 # 1 hr floof
=======
=======
      department: Epistemics
>>>>>>> parent of d439c5a962 (Revert "Merge branch 'VMSolidus-Psionic-Power-Refactor'")
=======
      department: Epistemics # DeltaV - Epistemics Department replacing Science
>>>>>>> parent of f5bf4d5bab (Giving pyrokinesis back to ifrit, and setting up base caster stat bonuses to roundstart casters)
      time: 3600
>>>>>>> parent of 462e91c2cc (aaaaaaaaa)
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  antagAdvantage: 5 # DeltaV - From 4 to 5
  canBeAntag: true # DeltaV - Mantis is no longer a Detective
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
    - type: MetapsionicPower

- type: startingGear
  id: ForensicMantisGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantis
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesBootsMantis
    head: ClothingHeadHatFezMantis
    id: ForensicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience # DeltaV - Mantis is part of Epistemics
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatMantis
    belt: ClothingBeltMantis
    # pocket2: ForensicScanner # DeltaV - Mantis is no longer a Detective
  innerClothingSkirt: ClothingUniformSkirtMantis
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled
